---
title: Eliana's Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: elabraha@umich.edu
description: Welcome to my blog. Enjoy :)
baseurl: "/blog"
url: http://elianaabraham.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
- jekyll-feed
