---
title: Eliana's Blog
author: Eliana Abraham
timezone: America/New_York
collections:
  pages:
    title: Pages
    output: true
  uploads:
    title: Uploads
    output: true
email: elabraha@umich.edu
description: Welcome to my blog. Enjoy :)
baseurl: "/blog"
url: https://elianaabraham.com
permalink: pretty
show_downloads: false
twitter_username: abrajamz
github_username: elabraha
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-category-pages
  - jekyll-asciinema
  - jekyll-tagging
navbar-links:
  Home: "/blog/"
  Author's Website: "https://www.elianaabraham.com"
  About Me: "/blog/about/"
  Archive: "/blog/archive/"
  Tags: "/blog/tags/"
  Categories: "/blog/categories/"
jekyll-compose: 
  auto_open: true
category_dir: "./_pages/categories/"
category_path: "categories/"
plugins_dir: "./_plugins/"
tag_page_layout: tag_page
tag_page_dir: tags
---