---
title: Eliana's Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  pages:
    title: Pages
    output: true
  uploads:
    title: Uploads
    output: true
email: elabraha@umich.edu
description: Welcome to my blog. Enjoy :)
baseurl: "/blog"
url: https://elianaabraham.com
show_downloads: false
twitter_username: abrajamz
github_username: elabraha
markdown: kramdown
theme: jekyll-theme-hacker
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
navbar-links:
  Home: "/blog"
  Author's Website: "https://www.elianaabraham.com"
  About Me: "/blog/about/"
  Archive: "/blog/archive/"
  Tags: 